name: c++ application

on:
  push:
    branches: ["test_qtmqtt"]


jobs:
  job:
    name: ${{ github.workflow }}
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
        #cmake安装
      - uses: lukka/get-cmake@latest

      - name: run-vcpkg
        run:  |
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          sudo apt install autoconf-archive
          vcpkg install qtmqtt
          
          
      - name: Run CMake+vcpkg
        run: |
          cmake . -B build -DEXECUTABLE_OUTPUT_PATH=target 
          cd build
          cmake --build . --config Release
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-mqtt
          path: ./build/target/Release

 
