name:  test_qt

on:
  push:
    branches: "test_qt"

jobs:
  job:
    name: ${{ github.workflow }}
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

       
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.3.2'
          host: 'windows'
          target: 'desktop'

      - name: Configure test project on windows
        run: qmake main.pro

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-qt
          path: .