name: c++ application

on:
  push:
    branches: ["main", "test_action","test_vcpkg"]

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2022]

    steps:
      - uses: actions/checkout@v3
     
      - run: .\first.ps1
      
      - run: echo "${{env.Json}}"
