name:  test_qt

on:
  push:
    branches: "test_qt"

jobs:
  job:
    name: ${{ github.workflow }}
    runs-on: [windows-latest]
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

       
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.3.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Configure test project on windows
      run: qmake
