name: c++ test

on:
  push:
    branches: [ "test"]
  
jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2022]

    steps:
      - uses: actions/checkout@v3
       
